
--mockup data
INSERT INTO NOTIFICATION (SPOILAGE, DATE_OF_CREATION, ITEM_ID, NAME) VALUES (2, CURRENT_TIMESTAMP(), 1, 'Mango');
INSERT INTO NOTIFICATION (SPOILAGE, DATE_OF_CREATION, ITEM_ID, NAME) VALUES (1, CURRENT_TIMESTAMP(), 1, 'Mango');
INSERT INTO NOTIFICATION (SPOILAGE, DATE_OF_CREATION, ITEM_ID, NAME) VALUES (0, CURRENT_TIMESTAMP(), 1, 'Mango');
INSERT INTO NOTIFICATION (SPOILAGE, DATE_OF_CREATION, ITEM_ID, NAME) VALUES (0, CURRENT_TIMESTAMP(), 1, 'Potatoes');
INSERT INTO NOTIFICATION (SPOILAGE, DATE_OF_CREATION, ITEM_ID, NAME) VALUES (2, CURRENT_TIMESTAMP(), 4, 'Milk');
INSERT INTO NOTIFICATION (SPOILAGE, DATE_OF_CREATION, ITEM_ID, NAME) VALUES (1, CURRENT_TIMESTAMP(), 2, 'Apples');
INSERT INTO NOTIFICATION (SPOILAGE, DATE_OF_CREATION, ITEM_ID, NAME) VALUES (2, CURRENT_TIMESTAMP(), 3, 'Milk');




