INSERT INTO ITEM (NAME, PRICE, QUANTITY, DATE_OF_PURCHASE, DATE_OF_EXPIRATION) VALUES ('Westminster', 5, 1, CURRENT_TIMESTAMP(), DATEADD(DAY,3,CURRENT_TIMESTAMP()));
INSERT INTO ITEM (NAME, PRICE, QUANTITY, DATE_OF_PURCHASE, DATE_OF_EXPIRATION) VALUES ('Milk', 1.90, 0.7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ITEM (NAME, PRICE, QUANTITY, DATE_OF_PURCHASE, DATE_OF_EXPIRATION) VALUES ('Mango', 1.90, 2, CURRENT_TIMESTAMP(), DATEADD(DAY,-3,CURRENT_TIMESTAMP()));
INSERT INTO ITEM (NAME, PRICE, QUANTITY, DATE_OF_PURCHASE) VALUES ('Butter', 0.90, 1.5, CURRENT_TIMESTAMP());

INSERT INTO CATEGORY (NAME) VALUES ('Fruit');
INSERT INTO CATEGORY (NAME) VALUES ('Vegetable');
INSERT INTO CATEGORY (NAME) VALUES ('Alcohol');


