CREATE TABLE ITEM(
  ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  PRICE DECIMAL(20, 2),
  SPOILAGE VARCHAR(16),
  QUANTITY DECIMAL(20, 2),
  DATE_OF_EXPIRATION DATE,
  DATE_OF_PURCHASE DATE
);

CREATE TABLE CATEGORY(
  CATEGORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL
);

CREATE TABLE ITEM_CATEGORY_LINK(
  ITEM_ID BIGINT,
  foreign key (ITEM_ID) references ITEM(ITEM_ID),
  CATEGORY_ID BIGINT,
  foreign key (CATEGORY_ID) references CATEGORY(CATEGORY_ID)
);

